### ISSUE TITLE
Great foundational work!

### ISSUE THREAD

**Issue by adamhrz** [Raizlabs/ios-template#1]
Nice work! just trying this on quick test project.

Thoughts: 
1. could you run pod install when as part of the scripts?
2. was suprised not to have the default for hockey app be the one that doesn’t trigger the curl
3. Any control over the DIR ordering? Looks alpha for now
4. maybe run synx at the end of code gen to cleanup (specifically noticed view folder exists in xcode but not on disk - would recommend creating each xcode folder on disk so create new file in view, for example, knows where to put it)

**Comment by KingOfBrian** [comment]
Thanks for the feedback @adamhrz!

1. Done
2. Done -- it now asks for the key, and if it is specified, it will update the fastfile
3. I ordered the directory better, and told `synx` not to sort it
4. Done

**Comment by adamhrz** [comment]
Awesome! Looking forward to my next lap with it!
